BostonGosari/Outline

- Outline/Outline/Source/DesignSystem/Extension/ColorExtension.swift
- #13 
- Color system 구현
<br>
ColorExtenstion 작성했습니다.
<br>
현재 `ColorSet 이름 + Color` 로 변수명을 설정했습니다. 이름은 추후 디자인 시스템이 구축되면 변경될 예정입니다.
xcode가 업데이트 되면서 `Color.first` 이런식으로 ColorSet에 있는 Color를 바로 사용할 수 있게 되었는데 ColorExtenstion이 필요 할까요...?
> design #13 : ColorExtenstion 작성

- Outline/Outline/Source/Manager/LocationManager.swift
- Outline/Outline/Source/View/RecomendedCourses/RecomendedCourseMap.swift
- Outline/Outline/Source/View/RecomendedCourses/RecommendedCourseView.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
- Outline/Outline/Source/View/Running/RunningView.swift
- Outline/Outline/Source/ViewModel/RecommendedCoursesViewModel.swift
- Outline/Outline/Source/ViewModel/RunningViewModel.swift
- #26 
- 러닝 진행 중 view 1차 구현
<br>
- 현재 러닝 상태에 따라 하단 버튼이 다르게 나오도록 구현했습니다.
```swift
private var runningButtonView: AnyView {
switch viewModel.runningType {
case .running:
AnyView(
HStack(alignment: .center) {
Spacer()
Button(action: {
viewModel.runningType = .pause
}, label: {
Image(systemName: "pause.fill")
.font(.system(size: 24))
.foregroundStyle(Color.black0Color)
.padding(24)
.background(
Circle()
.fill(Color.firstColor)
.stroke(.white0, style: .init())
)
})
.padding(.trailing, 64)
Button(action: {
}, label: {
Image(systemName: "scope")
.foregroundStyle(Color.black0Color)
.padding(19)
.background(
Circle()
.fill(Color.white)
)
})
.padding(.trailing, 32)
}
)
case .pause:
AnyView(
HStack {
/*longPress stop*/
Button(action: {
}, label: {
Image(systemName: "stop.fill")
.font(.system(size: …
```
> Feature #26 : RunningView 1차 구현

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/DesignSystem/Component/Confetti/Confetti.swift
- Outline/Outline/Source/DesignSystem/Component/Confetti/ConfettiShapes.swift
- Outline/Outline/Source/DesignSystem/Component/Confetti/ConfettiView.swift
- Outline/Outline/Source/Manager/HapticManager.swift
- #38  
- 컨페티 기능 구현
- 햅틱 기능 구현
<br>
- 아래와 같이 햅틱 매니저 구현하였습니다.
- 사용방법은 `HapticManager.impact(.soft)` 를 액션에 넣어서 사용하시면 됩니다.
```swift
final class HapticManager {
static func notification(type: UINotificationFeedbackGenerator.FeedbackType) {
let generator = UINotificationFeedbackGenerator()
generator.notificationOccurred(type)
}
static func impact(style: UIImpactFeedbackGenerator.FeedbackStyle) {
let generator = UIImpactFeedbackGenerator(style: style)
generator.impactOccurred()
}
}
```
- 아래와 같이 축하 애니메이션을 구현했습니다.
|기능|스크린샷|
|:--:|:--:|
|컨페티|<img src = "https://github.com/BostonGosari/Outline/assets/120548537/25781332-8a26-460d-9fe5-0a0c01cfbc7d" width ="250">|
<br>
```
뷰 작업 어디까지 완료되었는지 말씀해주세요!
```
> chore #38 :  햅틱, 컨페티 구현

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/Manager/PathGenerateManager.swift
- Outline/Outline/Source/OutlineApp.swift
- Outline/Outline/Source/View/DataTest/PathDrawingTestView.swift
#44 위도경도 데이터로 Path그리기
<br>
> `CLLocationCoordinate2D`의 위도경도값을 받아서 Path로 그리는 코드를 구현하였습니다. 간단한 로직은 아래와 같습니다.
1. coordinates들 중의 최소,최대 값을 구한뒤, max - min을 통하 전체 지도의 width, height를 구합니다.
2. 구한 `width, height`와 그리길 원하는 `View`의 `width`의 비율을 곱해줘서 `width, height` 중 긴 길이의 데이터가 해당 뷰에 맞게 상대 비율을 구합니다.
3. `Path`의 시작지점은 좌측상단에서 (0,0)으로 시작하므로 위에서 구한 `minLatitude, minLongitude `값을 저장합니다.
4. `coordinates`를 돌면서 해당 `coordinate`에서 `(0,0)`값에 해당하는 만큼의 비율을 뺀 뒤, `scale`을 곱한 값을 `path.addline`으로 그려나갑니다. 
> PathGenerateManager를 만들어서 Singleton으로 구현 코드를 사용할 수 있게 하였습니다.
> caculateLines에게 원하는 뷰의 size와 coordinates를 전달해주면 그린 Shape을 리턴하도록 구현하였습니다.
```swift
func caculateLines(width: Double, height: Double, coordinates: [CLLocationCoordinate2D]) -> some Shape {
let canvasData = calculateCanvaData(coordinates: coordinates, …
```
> feature #44 : 위도경도 데이터로 Path그리기

- Outline/Outline/Source/ViewModel/HomeTabViewModel.swift
- Outline/Outline/Source/ViewModel/RunningViewModel.swift
#78 
<br>
> runningType 누락으로인한 에러와 runningCourseId 누락 에러를 해결했습니다. 
<br>
```
- 현재 빌드가 되지 않는 상태여서 빠른 확인 부탁드립니다. 
```
> hotfix #78  runningType 누락 오류 해결

- Outline/Outline Watch/Source/View/SummaryView.swift
- Outline/Outline.xcodeproj/project.pbxproj
#64 
<br>
2초간 finalview 띄우고 SummaryView로 넘어가게 했습니다 
```
private func scheduleTimerToHideFinishView() {
Timer.scheduledTimer(withTimeInterval: 3.0, repeats: false) { _ in
withAnimation {
isShowingFinishView = false
}
}
}
```
```
if workoutManager.workout == nil {
ProgressView("Saving Workout")
.navigationBarHidden(true)
} else if isShowingFinishView {
FinishWatchView(completionPercentage: 100)
.onAppear {
scheduleTimerToHideFinishView()
}
.navigationBarHidden(true)
} else {
ScrollView {
```
<br>
<br>
```
간단한 작업이라서 금방 했습니다요 ..! 
```
> feat #64 : 뷰 연결

- Outline/Outline/Source/DesignSystem/Component/BackgroundBlur.swift
- Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
- Outline/Outline/Source/View/Record/MapView.swift
- Outline/Outline/Source/View/Record/RecordDetailView.swift
- Outline/Outline/Source/View/Record/RecordView.swift
#70 
<br>
running type별 filtering과 runnning Duration과 startDate기준으로 sorting을 하였습니다. 
```swift
private var sortingButtonLabel: String {
switch selectedSortOption {
case .latest:
return "최신순"
case .oldest:
return "오래된 순"
case .longestDistance:
return "최장거리"
case .shortestDistance:
return "최단거리"
}
}
private func updateSortDescriptors() {
switch selectedIndex {
case 0:
filteredRecords = Array(runningRecord)
case 1:
filteredRecords = runningRecord.filter { $0.runningType == "gpsArt" }
case 2:
filteredRecords = runningRecord.filter { $0.runningType == "free" }
default:
filteredRecords = []
}
switch selectedSortOption {
case .latest:
filteredRecords.sort(by: { $0.healthData?.startDate ?? Date() > $1.healthData?.startDate ?? Date() })
case .oldest:
filteredRecords.sort(by: { …
```
> feat #70 기록뷰 및 기록 디테일뷰 ui 구현 및 연결

- Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Outline/Outline/Source/Manager/LocationManager.swift
- Outline/Outline/Source/View/Running/RunningMap.swift
- #72 
- 사용자 이동경로 최적화
<br>
- 사용자의 이전 위치와 현재 위치를 비교하여 거리가 10 이상인 경우에만 배열에 저장한다.
```swift
func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
if let currentLocation = locations.last?.coordinate {
let distance: CLLocationDistance = 10
let  location = CLLocation(latitude: currentLocation.latitude, longitude: currentLocation.longitude)
if userLocations.isEmpty {
userLocations.append(currentLocation)
} else if let lastUserLocation = userLocations.last {
let lastLocation = CLLocation(latitude: lastUserLocation.latitude, longitude: lastUserLocation.longitude)
if  location.distance(from: lastLocation) >= distance {
userLocations.append(currentLocation)
}
}
}
}
```
<br>
|기능|스크린샷|
|:--:|:--:|
<br>
```
gif 곧 올릴게요....
```
> feature #72 : 사용자 이동경로 최적화

- Outline/Outline.xcodeproj/project.pbxproj
chore : upload projectfile
<br>
프로젝트 파일이 누락되어 추가로 pr올립니다. 
<br>
<br>
> chore : upload projectfile

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/View/Record/RecordDetailView.swift
- Outline/Outline/Source/View/Record/RecordView.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
- Outline/Outline/Source/View/Tab/HomeTabView.swift
- Outline/Outline/Source/ViewModel/RecordDetailViewModel.swift
- #86 
- RecordDetailView 구현
<br>
<br>
|기능|스크린샷|
|:--:|:--:|
<br>
```
이 곳에서 리뷰포인트를 작성해주세요.
```
> design #86 : RecordDetailView 구현

- Outline/Outline/Source/View/Record/RecordView.swift
#70 record view ui detail  수정
<br>
record Item 의 ui 디테일을 수정하였습니다. 
<br>
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://github.com/BostonGosari/Outline/assets/76644652/9ec6650c-d82b-46d2-9ad3-1640ba12d3e8" width ="250">|
<br>
> design : record view ui detail  수정

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/Manager/PathGenerateManager.swift
- Outline/Outline/Source/View/FreeRunning/FreeRunningMap.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
- Outline/Outline/Source/ViewModel/FinishRunningViewModel.swift
- Outline/Outline/Source/ViewModel/RecordDetailViewModel.swift
- #94 
- 데이터 흐름 오류 수정
<br>
- 데이터 파싱
```swift
runningData["킬로미터"] = String(format: "%.1f", healthData.totalRunningDistance/1000)
runningData["시간"] = formatDuration(healthData.totalTime)
runningData["평균 페이스"] = healthData.averagePace.formattedAveragePace()
runningData["BPM"] = "\(Int(healthData.averageHeartRate))"
runningData["칼로리"] = "\(healthData.totalEnergy)"
if healthData.averageCadence > 0 {
runningData["케이던스"] = "\(Int(healthData.averageCadence))"
} else {
runningData["케이던스"] = "0"
}
```
<br>
|기능|스크린샷|
|:--:|:--:|
<br>
> fix #94 :  데이터 오류 수정

- Outline/Outline Watch/Source/View/ControlsView.swift
#102
<br>
1. 기본 alert를 사용하려 했으나,  alert에 있는 ActionSheet를 이용할 시 버튼 커스텀이 되지 않아 따로 뷰를 구성하였습니다. `showingConfirmation`를 토글하여 뷰를 띄웁니다. 
```swift
Button {
showingConfirmation = true
} label: {
Image(systemName: "stop.fill")
.font(.system(size: 24))
.fontWeight(.black)
.foregroundColor(.white)
.padding()
}
```
2. 시트는 extension으로 빼두었습니다. 
```swift
extension ControlsView {
private func customExitSheet() -> some View {
ZStack {
Rectangle()
.ignoresSafeArea()
.foregroundStyle(.thinMaterial)
VStack {
Spacer()
Text("종료하시겠어요?")
.font(.headline)
.padding(.top, 20)
Spacer()
Button {
showingConfirmation = false
} label: {
Text("계속 진행하기")
.frame(maxWidth: .infinity)
.frame(height: 40)
.padding()
.background(
RoundedRectangle(cornerRadius: 20, style: .continuous)
.foregroundColor(Color.gray800.opacity(0.5)) …
```
> feat #106 : 러닝 종료 확인 alert

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Resource/KML/test.kml
- Outline/Outline/Source/Manager/PathGenerateManager.swift
- Outline/Outline/Source/View/Running/CourseGuidView.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
- #105 
- 미니 가이드 경로 1차 구현
<br>
- showBigGuid 상태에 따라 frame, padding 변경
- showBigGuid는 화면 터치에 따라 toggle
```swift
struct CourseGuidView: View {
@Binding var userLocations: [CLLocationCoordinate2D]
@Binding var showBigGuid: Bool
private let pathManager = PathGenerateManager.shared
let coursePathCoordinates: [CLLocationCoordinate2D]
let courseRotate: Double
var width: Double {
return showBigGuid ? 320 : 113
}
var height: Double {
return showBigGuid ? 480 : 168
}
var body: some View {
ZStack(alignment: showBigGuid ? .top : .topTrailing) {
if showBigGuid {
Color.black.opacity(0.5)
.ignoresSafeArea()
}
RoundedRectangle(cornerRadius: 20)
.fill(Color.gray.opacity(0.7))
.stroke(.white)
.overlay {
coursePath
.overlay {
userPath
}
.scaledToFit()
.rotationEffect(Angle(degrees: courseRotate)) …
```
> feature #105 : 미니 가이드 경로 1차 구현

- Outline/Outline/Source/Manager/PathGenerateManager.swift
- Outline/Outline/Source/View/Running/CourseGuidView.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
- #105 
- 미니 가이드 경로에서 사용자의 이동경로 그리기
<br>
- PathGenerateManager에서 기존 course 기반 canvas Data를 받아옵니다.
- canvas Data를 사용하여 userLocations를 path로 그립니다.
```swift
func calculateCanvaData(coordinates: [CLLocationCoordinate2D], width: Double, height: Double) -> CanvasData {
var minLat: Double = 90
var maxLat: Double = -90
var minLon: Double = 180
var maxLon: Double = -180
for coordinate in coordinates {
if coordinate.latitude < minLat {
minLat = coordinate.latitude
}
if coordinate.latitude > maxLat {
maxLat = coordinate.latitude
}
if coordinate.longitude < minLon {
minLon = coordinate.longitude
}
if coordinate.longitude > maxLon {
maxLon = coordinate.longitude
}
}
let calculatedHeight = (maxLat - minLat) * 1000000
let calculatedWidth = (maxLon - minLon) * 1000000
var relativeScale: Double = 0
if …
```
> feature #105 : 미니 가이드 경로

- Outline/Outline Watch/Source/Manager/WatchWorkoutManager.swift
- Outline/Outline Watch/Source/View/ControlsView.swift
- Outline/Outline Watch/Source/View/CourseListWatchView.swift
- Outline/Outline Watch/Source/View/ElapsedTimeView.swift
- Outline/Outline Watch/Source/View/MapWatchView.swift
- Outline/Outline Watch/Source/View/MetricsView.swift
- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/Manager/LocationManager.swift
- Outline/Shared/AppDelegate.swift
#106 
<br>
1. 워치에서 실시간페이스 및 평균 페이스 계산 및 포멧팅을 다시 했습니다. 다만 지금 뛸 수 있는 상황이 아니라서 내일 다시 확인해보려고 합니다 (ㅜㅜ)
```swift
//평균 페이스 계산
func calculateAveragePace(distance: Double, duration: TimeInterval) {
if distance > 0 && duration > 0 {
let averagePaceInSecondsPerMeter = duration / distance
let averagePaceInMinutesPerKilometer = averagePaceInSecondsPerMeter / 1000
self.averagePace = averagePaceInMinutesPerKilometer
} else {
self.averagePace = 0
}
}
// 실시간 페이스 계산
func calculatePaceFromSpeed(speed: Double) {
if speed > 0 {
let pace = 60 / (speed) * 60
self.pace = pace
} else {
self.pace = 0
}
}
```
```swift
func updateForStatistics(_ statistics: HKStatistics?) {
guard let statistics = statistics else { return }
DispatchQueue.main.async {
switch statistics.quantityType {
case …
```
> feat #106 워치 페이스 계산 검토 및 위치/헬스 권한 확인 

- Outline/Outline/Source/Manager/FunctionManager.swift
- Outline/Outline/Source/View/FininshRunning/FinishRunningMap.swift
- Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
- Outline/Outline/Source/ViewModel/FinishRunningViewModel.swift
- #108 
- 러닝 완료 뷰UI 수정
<br>
- popup 위치 변경
- popup 위에 navigationTitle이 뜨는 문제를 해결하기 위해 navigationTitle을 지우고 Text로 대체
```swift
if viewModel.isShowPopup {
RunningPopup(text: "기록이 저장되었어요.")
.frame(maxHeight: .infinity, alignment: .bottom)
.padding(.bottom, 712)
.transition(.move(edge: .top))
}
```
<br>
- polyline gradient 추가
```swift
func mapView(_ mapView: MKMapView, rendererFor overlay: MKOverlay) -> MKOverlayRenderer {
let renderer = MKGradientPolylineRenderer(overlay: overlay)
renderer.setColors([
UIColor(hex: "#333349"),
UIColor(hex: "#6478FF"),
UIColor(hex: "#DBFB6C")
], locations: [])
renderer.lineCap = .round
renderer.lineWidth = 10
return renderer
}
```
<br>
- 시간 데이터 수정
```swift
func formatMinuteSeconds(_ durationInMinutes: Double) -> String {
let minutes = Int(durationInMinutes) / 60 …
```
> design #108 : 러닝 완료뷰 UI 수정

- Outline/Outline/Source/DesignSystem/Extension/ViewExtension.swift
- Outline/Outline/Source/OutlineApp.swift
- Outline/Outline/Source/View/Share/CustomShareView.swift
- Outline/Outline/Source/View/Share/ImageShareView.swift
- Outline/Outline/Source/View/Share/ShareMainView.swift
- Outline/Outline/Source/View/Share/ShareMap.swift
#104 
closed #104 
<br>
> 공유 기능에서 저장한 이미지의 비율이 깨지고 화질이 좋지 않은 에러가 있었습니다. 해당 비율 문제 해결과 scale을 통해 UIScreen.bounds.scale을 통해 화질을 개선하였습니다. 
> .aspectRatio의 contentMode를 .fit에서 .fil로 변경하고 렌더하는 size를 구하는 코드를 하위 코드레벨로 변경해서 에러를 해결하였습니다. 
```swift
// .aspectRatio(1080/1920, contentMode: .fit)
.aspectRatio(1080/1920, contentMode: .fill)
```
> ViewExtension에서 scale을 UIScreen.main.scale로 변경해서 화질 문제를 개선하였습니다.
```swift
// format.scale = 1
format.scale = UIScreen.main.scale
```
<br>
|기능|스크린샷|
|:--:|:--:|
|Map 포함 공유뷰|<img src = "https://github.com/BostonGosari/Outline/assets/105622985/364de643-1e95-4e02-9d91-a91277da401e" width ="250">|
|경로만 보여주는 공유뷰|<img src = "https://github.com/BostonGosari/Outline/assets/105622985/5930fef2-09b8-4b7f-9fc5-3f83a08a40c8" width ="250">|
|사진 포함 공유뷰|<img src = …
> feature #104 : 이미지 렌더 비율 수정

- Outline/Outline Watch/Source/View/CourseListWatchView.swift
#120 
<br>
watch course list의 line cap과 join을 수정하였습니다. 
```swift
// .stroke(lineWidth: 4)
.stroke(style: StrokeStyle(lineWidth: 4, lineCap: .round, lineJoin: .round))
```
> 
<br>
|기능|스크린샷|
|:--:|:--:|
|Watch Course List View|<img src = "https://github.com/BostonGosari/Outline/assets/105622985/f35706dc-4804-4f38-ba06-f933a6e81fdc" width ="250">|
```
간단한 내용이라 PR이 민망하네요,, 코드 확인 부탁드립니다!
```
> feat #120 : watch course list의 line cap 수정

- Outline/Outline/Source/Manager/LocationManager.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
<br>
<br>
|기능|스크린샷|
|:--:|:--:|
<br>
```
이 곳에서 리뷰포인트를 작성해주세요.
```
> feat #110 : 도착지점 sheet 띄우기

- Outline/Outline/Source/View/GPSArtHome/BottomScrollView.swift
- Outline/Outline/Source/View/GPSArtHome/CardView.swift
- Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
- Outline/Outline/Source/View/GPSArtHome/Header.swift
#134
GPSArt 홈뷰의 전반적인 UI를 수정하였습니다.
<br>
1. 카드에 overlay된 텍스트의 가독성을 위해 gradient 추가 
```swift
.background {
Rectangle()
.foregroundColor(.clear)
.frame(width: 318, height: 187)
.background(
LinearGradient(
stops: [
Gradient.Stop(color: .black.opacity(0), location: 0.00),
Gradient.Stop(color: .black.opacity(0.7), location: 0.33),
Gradient.Stop(color: .black.opacity(0.8), location: 1.00)
],
startPoint: UnitPoint(x: 0.5, y: 0),
endPoint: UnitPoint(x: 0.5, y: 1)
)
)
.roundedCorners(45, corners: [.bottomLeft, .bottomRight])
}
```
2. 아래 수평 스크롤 stroke수정 
> 아이템의 height의 상하좌우로 shadow를 줘야하기 때문에, 전체 프레임의 height를 아이템의 height와 똑같이 잡으면 아랫부분이 잘려보입니다. 그래서 height를 1픽셀씩 크게 두었습니다. 
```swift
.frame(width: 164, height: 236)
.roundedCorners(5, corners: [.topLeft])
.roundedCorners(30, corners: [.topRight, …
```
> feat #134 : GPSArt 홈뷰 수정 

- Outline/Outline/Source/View/FreeRunning/FreeRunningHomeView.swift
#143 
<br>
1. 상단에 gradient를 추가했습니다. 
```swift
ZStack(alignment: .top) {
FreeRunningMap(userLocation: $userLocation)
.ignoresSafeArea()
Rectangle()
.foregroundColor(.clear)
.frame(maxWidth: .infinity, maxHeight: 358)
.background(
LinearGradient(
stops: [
Gradient.Stop(color: Color(red: 0.02, green: 0.01, blue: 0.15).opacity(0.4), location: 0.00),
Gradient.Stop(color: Color(red: 0.09, green: 0.07, blue: 0.39).opacity(0), location: 1.00)
],
startPoint: UnitPoint(x: 0.5, y: 0),
endPoint: UnitPoint(x: 0.5, y: 1)
)
)
```
2. 전체 백그라운드를 깔았습니다. 
```swift
Rectangle()
.foregroundColor(.clear)
.frame(maxWidth: .infinity, maxHeight: .infinity)
.background(.black.opacity(0.6))
```
<br>
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://github.com/BostonGosari/Outline/assets/76644652/02b1a3bc-3884-427d-85c5-6 …
> feat #143 : 자유러닝 홈뷰 ui detail

- Outline/Outline Watch/Source/Manager/WatchRunningManager.swift
- Outline/Outline Watch/Source/View/ControlsView.swift
- Outline/Outline Watch/Source/View/CourseListWatchView.swift
- Outline/Outline Watch/Source/View/FinishWatchView.swift
- Outline/Outline Watch/Source/View/MapWatchView.swift
- Outline/Outline Watch/Source/View/SummaryView.swift
- Outline/Outline Watch/Source/View/WatchTabView.swift
- Outline/Outline.xcodeproj/project.pbxproj
- #167 
- watchOS 데이터 분기 및 전송
- WatchRunningManager 생성
<br>
- 아래와 같은 변수를 관리합니다.
- 싱글톤이기 때문에 다양한 변수를 고려하여 watch와 iOS 분리하였습니다.
```swift
class WatchRunningManager: ObservableObject {
static var shared = WatchRunningManager()
private init() { }
@Published var userLocations: [CLLocationCoordinate2D] = []
@Published var changeRunningType = false
private let locationManager = CLLocationManager()
var startCourse: GPSArtCourse = GPSArtCourse()
var runningType: RunningType = .gpsArt
...
}
```
- 러닝 시작전 위치정보를 가져와 시작을 판별합니다.
```swift
func checkDistance(course: [Coordinate]) -> Bool {
guard let userLocation = locationManager.location?.coordinate else { return false }
guard let shortestDistance = calculateShortestDistance(from: userLocation, to: …
```
> feat #167 : watchOS 데이터 분기 및 전송

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Outline/Outline/Source/Model/Course/CourseModelType.swift
- Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
#165 
<br>
> FireStore에 저장된 GPSArtCourse의 description, startLocation, producer의 데이터를 추가했습니다. 
```swift
// CourseModelType.swift
struct GPSArtCourse: Codable, Hashable {
...
var description: String
var startLocation: Coordinate
var producer: String
init(..., description: String = "", startLocation: Coordinate = Coordinate(longitude: 0, latitude: 0), producer: String = "") {
...
self.description = description
self.startLocation = startLocation
self.producer = producer
}
init() {
...
self.description = ""
self.startLocation = Coordinate(longitude: 0, latitude: 0)
self.producer = "Outline"
}
}
```
<br>
|기능|스크린샷|
|:--:|:--:|
|CardDetailView|<img src = "https://github.com/BostonGosari/Outline/assets/105622985/49700d43-05b8-4049-98c7-dcd3dfcff1fe" width ="250">|
<br>
```
- 제작자는 기본적으로 Outline으로 …
```
> data #165 : FireStore 누락 데이터 추가

- Outline/Outline/Source/View/Running/RunningMapView.swift
- Outline/Outline/Source/View/Running/RunningView.swift
- Outline/Outline/Source/View/Running/WorkoutDataView.swift
- #177 
<br>
- 러닝뷰 이동 방식 변경
```swift
TabView(selection: $selection) {
RunningMapView(selection: $selection)
.tag(0)
.gesture(DragGesture())
WorkoutDataView(selection: $selection)
.tag(1)
.gesture(DragGesture())
}
.tabViewStyle(PageTabViewStyle(indexDisplayMode: .never))
```
- customSheet 구현 및 Confetti 추가
```swift
private var customSheet: some View {
ZStack {
Color.black.opacity(0.5)
VStack(spacing: 0) {
Text("오늘은, 여기까지")
.font(.title2)
.padding(.top, 56)
.padding(.bottom, 8)
Text("즐거운 러닝이었나요? 다음에 또 만나요! ")
.font(.subBody)
.padding(.bottom, 24)
Image("Finish10")
.resizable()
.frame(width: 120, height: 120)
.padding(.bottom, 45)
CompleteButton(text: "결과 페이지로", isActive: true) {
showCustomSheet = false
moveToFinishRunningView = true
}
}
.frame(height: UIScreen.main.bounds.height / 2) …
```
> design #177 : runningView 수정

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
- Outline/Outline/Source/View/Record/RecordDetailView.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
- Outline/Outline/Source/ViewModel/RunningMapViewModel.swift
- #187 
- map 최적화
<br>
- mapView의 기본 컴포넌트인 MapUserLocationButton을 사용해서 사용자가 mode에 따라 시점을 이동할 수 있게 구현
```swift
MapUserLocationButton(scope: mapScope)
.buttonBorderShape(.circle)
.tint(.white)
.controlSize(.large)
.frame(maxWidth: .infinity, alignment: .trailing)
.padding(.trailing, 32)
.padding(.bottom, 14)
```
- 나머지 조금조금 맵 수정했습니다.
<br>
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://github.com/BostonGosari/Outline/assets/55949986/c478f4d8-e916-4595-96ca-463b14dddb54" width ="250">|
<br>
```
QA 당시 가만히 있을 때 polyline이 튀는 오류가 있다고 했는데 아직 테스트를 못해서 추후에 다시 확인 후 수정하겠습니다.
```
> refactor #187 : map 최적화

- Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
#190 #197 
<br>
190 번 pr을 참고해주세요 
<br>
> feat #197 : 네트워크 예외 뷰 처리

- Outline/Outline Watch/Source/View/CourseListWatchView.swift
#199 199
<br>
```swift
if !viewModel.isLocationAuthorized {
isLocationPermissionSheetPresented = true
}
```
```swift
.sheet(isPresented: $isLocationPermissionSheetPresented) {
NavigationView {
LocationPermissionSheet()
}
.toolbar(.hidden, for: .navigationBar)
}
```
```swift
private func LocationPermissionSheet() -> some View {
VStack {
Image(systemName: "location.circle")
.resizable()
.frame(width: 43, height: 43)
.foregroundStyle(Color.first)
Spacer()
Text("OUTLINE iPhone을 실행해서\n위치 권한을 허용해주세요.")
.multilineTextAlignment(.center)
.font(Font.system(size: 13))
Spacer()
Button {
isLocationPermissionSheetPresented.toggle()
} label: {
Text("확인")
}
}
}
```
<br>
|기능|스크린샷|
|:--:|:--:|
|위치 권한 재확인 시트|<img src = "https://github.com/BostonGosari/Outline/assets/76644652/dbd08fde-6d3f-4346-9a6e-661a323bf …
> feat #199 : 러닝 시작전 권한 확인 및 분기 처리

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/ContentView.swift
- Outline/Outline/Source/Model/Auth/AppleAuthModel.swift
- Outline/Outline/Source/Model/Auth/AuthModel.swift
- Outline/Outline/Source/OutlineApp.swift
- Outline/Outline/Source/View/GPSArtHome/CardDetailView.swift
- Outline/Outline/Source/View/GPSArtHome/GPSArtHomeHeader.swift
- Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
- Outline/Outline/Source/View/LookAround/LookAroundView.swift
- Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
- Outline/Outline/Source/View/Onboarding/InputUserInfoView.swift
- Outline/Outline/Source/View/Onboarding/LoginView.swift
- Outline/Outline/Source/View/Onboarding/OnboardingNotificationAuthView.swift
- Outline/Outline/Source/View/Profile/ProfileHealthInfoView.swift
- Outline/Outline/Source/View/Profile/ProfileUserInfoView.swift
- Outline/Outline/Source/View/Profile/ProfileView.swift
- Outline/Outline/Source/View/Tab/HomeTabView.swift
- Outline/Outline/Source/View/Tab/TabBar.swift
- Outline/Outline/Source/ViewModel/InputUserInfoViewModel.swift
- Outline/Outline/Source/ViewModel/Login/LoginViewModel.swift
- Outline/Outline/Source/ViewModel/OnboardingLocationAuthViewModel.swift
- Outline/Outline/Source/ViewModel/ProfileViewModel.swift
#205
<br>
> LoginView에서는 이전에 카카오와 애플로 연결해두었던 기능을 AuthModel로 구현해두었습니다. 기존 계정이 있는 경우 바로 authState와 userId의 값을 각각 .login과 id값으로 설정하여 GPSArt화면으로 이동합니다. 
```swift 
// ContentView.swift
.onAppear {
AuthModel().handleCheckLoginState { res in
switch res {
case .success(let userId):
if let userId = userId {
self.userId = userId
self.authState = .login
} else {
if self.authState != .lookAround {
self.authState = .logout
}
}
case .failure(let failure):
if self.authState != .lookAround {
self.authState = .logout
}
print("fail to find userInfo \(failure)")
}
}
}
```
> 기존에 onboarding에서 설정한 데이터가 실제 데이터로 연결되지 않았는데 이제 onboarding에서 설정한 데이터는 FireStore에 업데이터 됩니다. 
```swift
// InputUserInfoViewModel.swift
func saveUserInfo(nickname: String) {
guard let userId = userId else {
print("userId is not find when …
```
> feat #205 : Login, 둘러보기, Profile뷰 연결

- Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Outline/Outline/Source/View/Profile/ProfileHealthInfoView.swift
- Outline/Outline/Source/View/Profile/ProfileUserInfoView.swift
- Outline/Outline/Source/View/Profile/ProfileView.swift
#212
<br>
> 기존 Profile뷰를 작업하는 중에 font가 custom으로 되었습니다. 해당 PR에서 머지하고 진행하려했지만 commit 에러들이 있는 상황이라 안전을 위해 기존 PR에서는 font 관련 내용을 주석처리해서 머지한 뒤, pull을 받아서 customFont로 다시 설정하였습니다.  
```swift
//.font(.tag)
.font(.customTag)
```
<br>
|기능|스크린샷|
|:--:|:--:|
|프로필뷰 font 변경|<img src = "https://github.com/BostonGosari/Outline/assets/105622985/aba950b8-a27e-4a2b-8b81-8db2d5df83d5" width ="250">|
<br>
```
디자인 및 기능에 대한 변경 사항은 없고 customFont만 적용해두었습니다. 
```
> design #212 : Profile에서 customFont 적용

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Outline/Outline/Source/OutlineApp.swift
- Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
- Outline/Outline/Source/View/NewRunning/NewRunningMetricsView.swift
- Outline/Outline/Source/View/NewRunning/NewRunningNavigationView.swift
- Outline/Outline/Source/View/NewRunning/NewRunningView.swift
- #237 
- 새로운 러닝뷰 UI 생성
<br>
- 러닝뷰 맵뷰 생성
- 러닝뷰 상단 네비게이션 생성
- 러닝뷰 하단 데이터뷰 생성
- 뷰 구성은 아래와 같습니다.
```swift
var body: some View {
ZStack {
map
navigation
metrics
}
}
```
<br>
|기능|스크린샷|상세설명|
|:--:|:--:|:--:|
|하단 컨트롤|<img src = "https://github.com/BostonGosari/Outline/assets/120548537/c4daab8a-a812-4b33-bcf7-aeae98076e6c" width ="250">|일시정지를 누르면 디테일한 수치가 나타납니다. 재생을 누르게 되면 디테일한 수치가 내려갑니다. 일시정지를 누른 상태에서 디테일을 우측 버튼으로 사라지게 하면 다시 재생을 눌러야 좌측에 시간이 나타납니다.|
|상단 컨트롤|<img src = "https://github.com/BostonGosari/Outline/assets/120548537/6eb54e5a-b34e-491a-96cd-652dba06c397" width ="250">|드래그나 클릭으로 인터렉션 가능|
|하단 컨트롤|<img src = "https://github.com/BostonGosari/Outline/assets/120548537/0919b9e6-0926-4c72-9ce3-91cb3743f45e" width ="250">|네비게이션이 나타난 상태라면 어떤 버튼을 눌러도 네비게이션 시트가 사라지게|
```
- 인터렉션 관련되어 논의되지 않는 부분은 임의로 …
```
> feat #237 : 새로운 러닝뷰 UI

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/Utils/Extension/DoubleExtension.swift
#243 
<br>
> 러닝 종료 시 pace 데이터를 전환하는 과정에서 NaN또는 infinity라는 에러가 나왔습니다. 
> 위에 에러가 다양한 상황에서 발생할 수 있기 때문에 조건을 View나 ViewModel에 주는 것이 아닌 formattedAveragePace에 주어 문제를 해결하였습니다.
```swift
func formattedAveragePace() -> String {
if self.isZero || self.isNaN || self.isInfinite {
return "-'--''"
}
let minutes = Int(self / 60)
let seconds = Int(self) % 60
return String(format: "%d'%02d''", minutes, seconds)
}
```
<br>
|기능|스크린샷|
|:--:|:--:|
|러닝 종료 앱 강제 종료|<img src = "https://github.com/BostonGosari/Outline/assets/105622985/cbf560bb-3ef3-4480-af85-f37be0a776b4" width ="250">|
|러닝 종료 해결|<img src = "https://github.com/BostonGosari/Outline/assets/105622985/acc567c2-fb69-4589-bf61-df74531ccbfe" width ="250">|
<br>
```
```
> fix #243 : Double Extension에서 fommatedAveragePace 기능 수정

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/Manager/LocationManager.swift
- Outline/Outline/Source/Manager/RunningStartManager.swift
- Outline/Outline/Source/View/FininshRunning/FinishRunningView.swift
- Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
- Outline/Outline/Source/View/NewRunning/NewRunningMetricsView.swift
- Outline/Outline/Source/View/NewRunning/NewRunningView.swift
- Outline/Outline/Source/View/Tab/HomeTabView.swift
- #247 
- 러닝뷰 데이터 연결
<br>
- NewRunningMapView와 NewRunningMetricsView에 `RunningStartManager`와 `RunningDataManager`를 호출해 데이터 연결
- RunningMapView에서 `.onChange(of: CLLocationManager().location)`가 정상적으로 동작하지 않았던 문제를 해결하기위해 LocationManager 구현
- CLLocationManagerDelegate의 `didUpdateLocations`를 사용하여 사용자의 위치정보를 업데이트
```swift
class LocationManager: NSObject, ObservableObject, CLLocationManagerDelegate {
@Published var userLocations: [CLLocationCoordinate2D] = []
private var locationManager = CLLocationManager()
override init() {
super.init()
locationManager.delegate = self
locationManager.requestWhenInUseAuthorization()
locationManager.distanceFilter = 10
locationManager.startUpdatingLocation()
}
func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
if let …
```
> feat #247 : NewRunningView 연결

- Outline/Outline/Source/View/NewRunning/NewRunningMapView.swift
- Outline/Outline/Source/View/NewRunning/NewRunningView.swift
- Outline/Outline/Source/View/Running/CourseGuideView.swift
- Outline/Outline/Source/View/Running/RunningMapView.swift
- #268 
<br>
- 러닝 중 stop Button이 2초 이상 눌리는 시점에 runningDataManger의 userLocations에 locationManger의 userLocations을 저장하는 구문 작성
```swift
runningDataManager.userLocations = locationManager.userLocations
```
<br>
|기능|스크린샷|
|:--:|:--:|
|결과 뷰|<img src = "https://github.com/BostonGosari/Outline/assets/55949986/678b290e-ec34-48ed-b5a7-6054fee69edb" width ="250">|
> fix #268 : userLocation 저장 문제 해결

- Outline/Outline/Source/Model/Course/CourseModelType.swift
#275
<br>
> UI가 수정되면서 FireStore에 있는 데이터가 수정되어야 했습니다. 
```swift
struct GPSArtCourse: Codable, Hashable {
...
var thumbnailNeon: String
...
```
```swift
struct HotSpot: Codable, Hashable {
...
var spotDescription: String
...
}
```
```swift
struct Navigation: Codable, Hashable {
var distance: Double
var nextDirection: String
var longitude: Double
var latitude: Double
var alertMessage: String
}
```
```
Navigation과 Hotspot의 경우 기존에 수정이 예상되었던 부분이서 빠르게 수정할 수 있었습니다. 수정 내용이 문제가 되는 부분이 있다면 리뷰바랍니다:)
```
> feat #275 : CourseModel 데이터 수정

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/Model/Place.swift
- Outline/Outline/Source/View/GPSArtHome/CardDetailInformationView.swift
- Outline/Outline/Source/View/GPSArtHome/CardDetailMap.swift
- #299
<br>
- map에 pin으로 표현하기 위해 Place model 생성
```swift
struct Place: Identifiable, Hashable {
let id: Int
let title: String
let spotDescription: String
let location: CLLocationCoordinate2D
static func == (lhs: Place, rhs: Place) -> Bool {
lhs.id == rhs.id
}
func hash(into hasher: inout Hasher) {
hasher.combine(id)
}
}
````
- 지도가 나타날 때 selectedCourse에 담긴 정보들을 places 배열에 저장 
``` swift
places.append(
Place(
id: 0,
title: "\(selectedCourse.locationInfo.locality) \(selectedCourse.locationInfo.subLocality) \(selectedCourse.locationInfo.throughfare) \(selectedCourse.locationInfo.subThroughfare)",
spotDescription: "시작 위치",
location: CLLocationCoordinate2D(latitude: selectedCourse.startLocation.latitude, longitude: selectedCourse.startLocation.longitude)
)
)
for (index, place) in …
```
> feat #299 : detail 지도뷰 구현

- Outline/Outline/Source/View/Onboarding/HealthAuthView.swift
- Outline/Outline/Source/View/Onboarding/InputNicknameView.swift
- Outline/Outline/Source/ViewModel/InputNicknameViewModel.swift
#303 
<br>
> InputNicknameViewModel 싱글톤으로 nickname 오류 해결
<br>
```
기존에 이름을 빈칸으로 추가되던 에러 수정
```
> hotfix #303 : 계정생성시 이름 추가 에러 수정

- Outline/Outline.xcodeproj/project.pbxproj
- Outline/Outline/Source/View/Record/NewRecordDetailView.swift
- Outline/Outline/Source/View/Record/RecordView.swift
- Outline/Outline/Source/ViewModel/RecordDetailViewModel.swift
<br>
<br>
|기능|스크린샷|
|:--:|:--:|
<br>
```
이 곳에서 리뷰포인트를 작성해주세요.
```
> feat #313 : 디테일 뷰 연결

- Outline/Outline/Source/View/Share/SharePhotoView.swift
- #319
- PNG 를 랜더링 합니다.
<br>
```swift
extension View {
@MainActor func render(scale: CGFloat) -> UIImage? {
let renderer = ImageRenderer(content: self)
renderer.scale = scale
return renderer.uiImage
}
}
```
- 투명하게 저장되어서 그대로 저장하면 배경이 하얀색으로 저장되는 것 같습니다.
```swift
private func renderShareView() {
image = viewForShare
.render(scale: scale)
}
private func renderShareViewForSaving() {
image = viewForShare
.asImage(size: size)
}
```
|설명|투명하게 해서 저장했을 때|asImage 로 수정 후|
|:--:|:--:|--:|
|스크린샷|<img src = "https://github.com/BostonGosari/Outline/assets/120548537/63d5902d-811a-4318-84d5-15a6d2ff3f04" width ="150">|<img src = "https://github.com/BostonGosari/Outline/assets/120548537/0ac6cb12-1f24-4f39-8650-7fae7ec24206" width ="150">|
- 글씨가 검은색으로 보이는 부분도 수정하였습니다. (스크린샷은 적용 안되어 있음)
<br>
|기능|스크린샷| …
> feat #319 : 투명 랜더링 기능 추가

- Outline/Outline/Source/Utils/Component/Card/BigCard.swift
- Outline/Outline/Source/View/GPSArtHome/GPSArtHomeHeader.swift
- Outline/Outline/Source/View/GPSArtHome/GPSArtHomeView.swift
<br>
<br>
|기능|스크린샷|
|:--:|:--:|
<br>
```
이 곳에서 리뷰포인트를 작성해주세요.
```
> fix #330 : QA 반영
